<schema xmlns="http://purl.oclc.org/dsdl/schematron" queryBinding="xslt2"><title> Schematron file for REPC_IN002120NL - Overdracht Acute Fase bericht </title><ns uri="urn:hl7-org:v3" prefix="hl7"/><ns uri="urn:hl7-org:v3" prefix="cda"/><ns uri="http://www.w3.org/2001/XMLSchema-instance" prefix="xsi"/>
   <!-- Add extra namespaces --><ns uri="http://www.w3.org/XML/1998/namespace" prefix="xml"/>
   <!-- Include realm specific schematron --><!--Include datatype abstract schematrons--><pattern><include href="include/DTr1_ANY.sch"/><include href="include/DTr1_AD.sch"/><include href="include/DTr1_AD.NL.sch"/><include href="include/DTr1_AD.DE.sch"/><include href="include/DTr1_BIN.sch"/><include href="include/DTr1_ED.sch"/><include href="include/DTr1_ST.sch"/><include href="include/DTr1_SC.sch"/><include href="include/DTr1_ENXP.sch"/><include href="include/DTr1_ADXP.sch"/><include href="include/DTr1_BL.sch"/><include href="include/DTr1_CD.sch"/><include href="include/DTr1_CE.sch"/><include href="include/DTr1_CV.sch"/><include href="include/DTr1_CO.sch"/><include href="include/DTr1_CS.sch"/><include href="include/DTr1_CS.LANG.sch"/><include href="include/DTr1_EN.sch"/><include href="include/DTr1_TN.sch"/><include href="include/DTr1_ON.sch"/><include href="include/DTr1_PN.sch"/><include href="include/DTr1_II.sch"/><include href="include/DTr1_II.NL.BSN.sch"/><include href="include/DTr1_II.NL.URA.sch"/><include href="include/DTr1_II.NL.UZI.sch"/><include href="include/DTr1_II.NL.AGB.sch"/><include href="include/DTr1_II.AT.DVR.sch"/><include href="include/DTr1_II.AT.ATU.sch"/><include href="include/DTr1_II.AT.BLZ.sch"/><include href="include/DTr1_II.AT.KTONR.sch"/><include href="include/DTr1_IVL.sch"/><include href="include/DTr1_IVL_INT.sch"/><include href="include/DTr1_INT.sch"/><include href="include/DTr1_INT.NONNEG.sch"/><include href="include/DTr1_INT.POS.sch"/><include href="include/DTr1_IVL_PQ.sch"/><include href="include/DTr1_IVL_TS.sch"/><include href="include/DTr1_TS.sch"/><include href="include/DTr1_TS.DATE.sch"/><include href="include/DTr1_TS.DATE.FULL.sch"/><include href="include/DTr1_TS.DATE.MIN.sch"/><include href="include/DTr1_TS.DATETIME.MIN.sch"/><include href="include/DTr1_QTY.sch"/><include href="include/DTr1_PQ.sch"/><include href="include/DTr1_PQR.sch"/><include href="include/DTr1_SXPR_TS.sch"/><include href="include/DTr1_RTO.sch"/><include href="include/DTr1_RTO_QTY_QTY.sch"/><include href="include/DTr1_SD.TEXT.sch"/><include href="include/DTr1_SXCM.sch"/><include href="include/DTr1_PIVL_TS.sch"/><include href="include/DTr1_EIVL_TS.sch"/><include href="include/DTr1_URL.sch"/><include href="include/DTr1_TEL.sch"/><include href="include/DTr1_TEL.AT.sch"/><include href="include/DTr1_URL.NL.EXTENDED.sch"/></pattern>

   <!-- Include the project schematrons related to scenario acufov -->

<!-- acufov --><include href="include/2.16.840.1.113883.2.4.6.10.90.63-2013-11-08T000000.sch"/>

   <!-- Include schematrons from templates with explicit * or ** context (but no representing templates), only those used in scenario template -->



<!-- includes --></schema>